# http server configuration
http:
  # listens on port
  port: 8996
  # trace requests/responses
  trace: ${HTTP_TRACE_ENABLED|false}
  # write-timeout-sec covers the time from the end of the request header read to the end of the response write
  write-timeout-sec: ${HTTP_WRITE_TIMEOUT_SEC|60}
  # read-timeout-sec covers the time from when the connection is accepted to when the request body is fully read
  read-timeout-sec: ${HTTP_READ_TIMEOUT_SEC|60}
  # http server write buffer size
  write-buffer-size-bytes: ${HTTP_WRITE_BUFFER_SIZE_BYTES|1024}
  # http server read buffer size
  read-buffer-size-bytes: ${HTTP_READ_BUFFER_SIZE_BYTES|1024}

# storages configuration
storages:
  # database client
  database:
    # local path to migration folder
    mig-path: ${DECISIONROOT|}/db/migrations
    # db master config
    master:
      # database name
      dbname: ${DB_MASTER_NAME|decision}
      # db username
      user: decision
      # db password
      password: ${DB_MASTER_PASSWORD|decision}
      # db port
      port: ${DB_MASTER_PORT|55432}
      # host for master (read-write) database
      host: ${DB_MASTER_HOST|localhost}

# logging configuration
log:
  # level
  level: ${DECISION_LOG_LEVEL|trace}
  # output format (plain, json)
  format: ${DECISION_LOG_FORMAT|plain}
  # if service info is appeared in log
  service: ${DECISION_LOG_SERVICE|true}
  # if context info is appeared in log
  context: ${DECISION_LOG_CONTEXT|true}





