// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	kit "github.com/mikhailbolshakov/decision/kit"
	mock "github.com/stretchr/testify/mock"
)

// AppErrBuilder is an autogenerated mock type for the AppErrBuilder type
type AppErrBuilder struct {
	mock.Mock
}

// Business provides a mock function with given fields:
func (_m *AppErrBuilder) Business() kit.AppErrBuilder {
	ret := _m.Called()

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func() kit.AppErrBuilder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// C provides a mock function with given fields: ctx
func (_m *AppErrBuilder) C(ctx context.Context) kit.AppErrBuilder {
	ret := _m.Called(ctx)

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func(context.Context) kit.AppErrBuilder); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// Err provides a mock function with given fields:
func (_m *AppErrBuilder) Err() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// F provides a mock function with given fields: fields
func (_m *AppErrBuilder) F(fields kit.KV) kit.AppErrBuilder {
	ret := _m.Called(fields)

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func(kit.KV) kit.AppErrBuilder); ok {
		r0 = rf(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// GrpcSt provides a mock function with given fields: status
func (_m *AppErrBuilder) GrpcSt(status uint32) kit.AppErrBuilder {
	ret := _m.Called(status)

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func(uint32) kit.AppErrBuilder); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// HttpSt provides a mock function with given fields: status
func (_m *AppErrBuilder) HttpSt(status uint32) kit.AppErrBuilder {
	ret := _m.Called(status)

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func(uint32) kit.AppErrBuilder); ok {
		r0 = rf(status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// Panic provides a mock function with given fields:
func (_m *AppErrBuilder) Panic() kit.AppErrBuilder {
	ret := _m.Called()

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func() kit.AppErrBuilder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// System provides a mock function with given fields:
func (_m *AppErrBuilder) System() kit.AppErrBuilder {
	ret := _m.Called()

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func() kit.AppErrBuilder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// Type provides a mock function with given fields: t
func (_m *AppErrBuilder) Type(t string) kit.AppErrBuilder {
	ret := _m.Called(t)

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func(string) kit.AppErrBuilder); ok {
		r0 = rf(t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

// Wrap provides a mock function with given fields: cause
func (_m *AppErrBuilder) Wrap(cause error) kit.AppErrBuilder {
	ret := _m.Called(cause)

	var r0 kit.AppErrBuilder
	if rf, ok := ret.Get(0).(func(error) kit.AppErrBuilder); ok {
		r0 = rf(cause)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.AppErrBuilder)
		}
	}

	return r0
}

type mockConstructorTestingTNewAppErrBuilder interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppErrBuilder creates a new instance of AppErrBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppErrBuilder(t mockConstructorTestingTNewAppErrBuilder) *AppErrBuilder {
	mock := &AppErrBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
