// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	kit "github.com/mikhailbolshakov/decision/kit"
	mock "github.com/stretchr/testify/mock"
)

// CLoggerFunc is an autogenerated mock type for the CLoggerFunc type
type CLoggerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *CLoggerFunc) Execute() kit.CLogger {
	ret := _m.Called()

	var r0 kit.CLogger
	if rf, ok := ret.Get(0).(func() kit.CLogger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(kit.CLogger)
		}
	}

	return r0
}

type mockConstructorTestingTNewCLoggerFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewCLoggerFunc creates a new instance of CLoggerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCLoggerFunc(t mockConstructorTestingTNewCLoggerFunc) *CLoggerFunc {
	mock := &CLoggerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
