// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	configuro "github.com/mikhailbolshakov/decision/kit/config/configuro"
	mock "github.com/stretchr/testify/mock"
)

// ConfigOptions is an autogenerated mock type for the ConfigOptions type
type ConfigOptions struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *ConfigOptions) Execute(_a0 *configuro.Config) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*configuro.Config) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewConfigOptions interface {
	mock.TestingT
	Cleanup(func())
}

// NewConfigOptions creates a new instance of ConfigOptions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConfigOptions(t mockConstructorTestingTNewConfigOptions) *ConfigOptions {
	mock := &ConfigOptions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
