// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Validatable is an autogenerated mock type for the Validatable type
type Validatable struct {
	mock.Mock
}

// Validate provides a mock function with given fields:
func (_m *Validatable) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewValidatable interface {
	mock.TestingT
	Cleanup(func())
}

// NewValidatable creates a new instance of Validatable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewValidatable(t mockConstructorTestingTNewValidatable) *Validatable {
	mock := &Validatable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
