// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"

	websocket "github.com/gorilla/websocket"
)

// WsUpgrader is an autogenerated mock type for the WsUpgrader type
type WsUpgrader struct {
	mock.Mock
}

// Set provides a mock function with given fields: router, upgrader
func (_m *WsUpgrader) Set(router *mux.Router, upgrader *websocket.Upgrader) {
	_m.Called(router, upgrader)
}

type mockConstructorTestingTNewWsUpgrader interface {
	mock.TestingT
	Cleanup(func())
}

// NewWsUpgrader creates a new instance of WsUpgrader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWsUpgrader(t mockConstructorTestingTNewWsUpgrader) *WsUpgrader {
	mock := &WsUpgrader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
